#!/usr/bin/env python
import autowaf

def build(bld):
	# Headers
	bld.install_files('${INCLUDEDIR}/ingen/gui', bld.path.ant_glob('*.hpp'))

	obj = bld(features = 'cxx cxxshlib')
	obj.source = '''
		App.cpp
		BreadCrumbs.cpp
		Configuration.cpp
		ConnectWindow.cpp
		Connection.cpp
		ControlPanel.cpp
		Controls.cpp
		GladeFactory.cpp
		LoadPatchWindow.cpp
		LoadPluginWindow.cpp
		LoadRemotePatchWindow.cpp
		MessagesWindow.cpp
		NewSubpatchWindow.cpp
		NodeControlWindow.cpp
		NodeMenu.cpp
		NodeModule.cpp
		ObjectMenu.cpp
		PatchCanvas.cpp
		PatchPortModule.cpp
		PatchTreeWindow.cpp
		PatchView.cpp
		PatchWindow.cpp
		Port.cpp
		PortMenu.cpp
		PortPropertiesWindow.cpp
		PropertiesWindow.cpp
		RenameWindow.cpp
		SubpatchModule.cpp
		ThreadedLoader.cpp
		Window.cpp
		WindowFactory.cpp
		ingen_gui.cpp
	'''

	if bld.env['HAVE_CURL'] != 0:
		obj.source += 'UploadPatchWindow.cpp'

	obj.export_includes = ['.']
	obj.includes        = ['.', '..', '../..', '../common', '../client', '../module']
	obj.name            = 'libingen_gui'
	obj.target          = 'ingen_gui'
	obj.install_path    = '${LIBDIR}'
	obj.use             = 'libingen_shared libingen_module libingen_client libingen_serialisation'
	autowaf.use_lib(bld, obj, '''
		CURL
		FLOWCANVAS
		GLADEMM
		GLIBMM
		GNOMECANVASMM
		GTKMM
		RAUL
		REDLANDMM
		SIGCPP
		LV2CORE
		SLV2
		SOUP
		XML2
	''')

	# GUI runtime files
	bld.install_files('${DATADIR}/ingen', 'ingen_gui.glade')


