#!/usr/bin/env python
import Params
import autowaf

def build(bld):
	obj = bld.create_obj('cpp', 'shlib')
	obj.source = '''
		Parser.cpp
		Serialiser.cpp
		serialisation.cpp
	'''
	obj.includes     = ['.', '..', '../common']
	obj.name         = 'libingen_serialisation'
	obj.target       = 'ingen_serialisation'
	obj.inst_dir     = bld.env()['LIBDIRNAME'] + 'ingen'
	obj.uselib_local = 'libingen_shared'
	autowaf.use_lib(bld, obj, 'GLIBMM LV2CORE SLV2 RAUL REDLANDMM')

