#!/usr/bin/env python
from waflib.extras import autowaf as autowaf

def build(bld):
    if bld.is_defined('HAVE_LIBLO'):
        obj = bld(features        = 'cxx cxxshlib',
                  source          = '''OSCClientSender.cpp
                                       OSCEngineReceiver.cpp
                                       OSCSender.cpp
                                       ingen_osc_server.cpp''',
                  includes        = ['.', '../..'],
                  name            = 'libingen_osc_server',
                  target          = 'ingen_osc_server',
                  install_path    = '${LIBDIR}',
                  use             = 'libingen_server')
        autowaf.use_lib(bld, obj, 'RAUL LIBLO')

        obj = bld(features        = 'cxx cxxshlib',
                  source          = '''OSCClientReceiver.cpp
                                       OSCEngineSender.cpp
                                       OSCSender.cpp
                                       ingen_osc_client.cpp''',
                  includes        = ['.', '../..'],
                  name            = 'libingen_osc_client',
                  target          = 'ingen_osc_client',
                  install_path    = '${LIBDIR}',
                  use             = 'libingen_client')
        autowaf.use_lib(bld, obj, 'RAUL LIBLO')
