/* This file is part of Ingen.
 * Copyright (C) 2007 Dave Robillard <http://drobilla.net>
 * 
 * Ingen is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 * 
 * Ingen is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 */

#include <iostream>
#include <unistd.h>
#include <raul/Path.h>
#include <raul/RDFWorld.h>
#include "OSCModelEngineInterface.h"
#include "Loader.h"
#include "PatchModel.h"
#include "cmdline.h"  // generated by gengetopt

using std::cout; using std::endl; 

using namespace Ingen::Client;

int main(int argc, char** argv)
{
	const char* engine_url  = NULL;
	int         client_port = 0;
	
	/* **** Parse command line options **** */

	gengetopt_args_info args_info;
	if (cmdline_parser (argc, argv, &args_info) != 0)
		return 1;

	if (args_info.engine_url_given) {
		engine_url = args_info.engine_url_arg;
	} else {
		cout << "[Main] No engine URL specified.  Attempting to use osc.udp://localhost:16180" << endl;
		engine_url = "osc.udp://localhost:16180";
	}	

	if (args_info.client_port_given)
		client_port = args_info.client_port_arg;


	/* **** Mr. Spock.. Engage **** */

	Raul::RDF::World rdf_world;
	rdf_world.add_prefix("xsd", "http://www.w3.org/2001/XMLSchema#");
	rdf_world.add_prefix("ingen", "http://drobilla.net/ns/ingen#");
	rdf_world.add_prefix("ingenuity", "http://drobilla.net/ns/ingenuity#");
	rdf_world.add_prefix("lv2", "http://lv2plug.in/ontology#");
	rdf_world.add_prefix("rdfs", "http://www.w3.org/2000/01/rdf-schema#");
	rdf_world.add_prefix("doap", "http://usefulinc.com/ns/doap#");

	SharedPtr<OSCModelEngineInterface> engine(new OSCModelEngineInterface(engine_url));
	Loader loader(engine, &rdf_world);
	
	/* Connect to engine */
	engine->attach(-1, client_port);
	engine->activate();
	//engine->register_client(NULL); // FIXME

	//int id = engine->get_next_request_id();
	//engine->set_wait_response_id(id);
	//engine->load_plugins(id);
	//engine->wait_for_response();
	/* FIXME: Make this work like this:
	 * engine->load_plugins();
	 * engine->wait_for_response();
	 */

	// Load patches
	for (uint i=0; i < args_info.inputs_num; ++i) {
		cerr << "FIXME: load patch under root" << endl;
		cerr << "Load " << args_info.inputs[i] << endl;
		loader.load(&rdf_world, string("file:") + args_info.inputs[i], Path("/"), "");
	}
	
	return 0;
}
