.TH INGEN 1 "04 Apr 2015"

.SH NAME
.B ingen \- A realtime modular audio processor

.SH SYNOPSIS
ingen [OPTION]...

.SH OPTIONS

.TP
\fB\-C, \-\-client\-port\fR=\fIINT\fR
Client port
.TP
\fB\-c, \-\-connect\fR=\fISTRING\fR
Connect to engine URI
.TP
\fB\-e, \-\-engine\fR
Run (JACK) engine
.TP
\fB\-E, \-\-engine-port\fR=\fIINT\fR
Engine listen port
.TP
\fB\-\-graph\-directory\fR
Default directory for opening graphs
.TP
\fB\-g, \-\-gui\fR
Launch the GTK graphical interface
.TP
\fB\-h, \-\-help\fR
Print this help message
.TP
\fB\-\-human\-names\fR
Show human names in GUI
.TP
\fB\-n, \-\-jack\-name\fR=\fISTRING\fR
JACK name
.TP
\fB\-s, \-\-jack\-server\fR=\fISTRING\fR
JACK server name
.TP
\fB\-l, \-\-load\fR=\fISTRING\fR
Load graph
.TP
\fB\-L, \-\-path\fR=\fISTRING\fR
Target path for loaded graph
.TP
\fB\-\-port\-labels\fR
Show port labels in GUI
.TP
\fB\-q, \-\-queue-size\fR=\fIINT\fR
Event queue size
.TP
\fB\-r, \-\-run\fR
Run script
.TP
\fB\-S, \-\-socket\fR=\fISTRING\fR
Engine socket path
.TP
\fB\-u, \-\-uuid\fR=\fISTRING\fR
JACK session UUID
.TP
\fB\-V, \-\-version\fR
Print version information

.SH AUTHOR
Ingen was written by David Robillard <d@drobilla.net>

.SH COPYRIGHT
Copyright \(co 2005-2015 David Robillard.
.br
License: <https://www.gnu.org/licenses/agpl-3.0>
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.

.SH "SEE ALSO"
<http://drobilla.net/software/ingen>
