#!/usr/bin/env python
import Params
import autowaf

def build(bld):
	obj = bld.create_obj('cpp', 'shlib')
	obj.source = '''
		Builder.cpp
		ClashAvoider.cpp
		LV2Features.cpp
		LV2URIMap.cpp
		Store.cpp
	'''
	if bld.env()['HAVE_LIBLO']:
		obj.source += ' OSCSender.cpp '
	obj.includes = ['.', '../', '../common']
	obj.name     = 'libingen_shared'
	obj.target   = 'ingen_shared'
	obj.vnum     = '0.0.0'
	autowaf.use_lib(bld, obj, 'GLIBMM LV2CORE SLV2 RAUL REDLANDMM')

