#!/usr/bin/env python
from waflib.extras import autowaf as autowaf

def build(bld):
    obj = bld(features        = 'cxx cxxshlib',
              export_includes = ['../..'],
              includes        = ['../..'],
              name            = 'libingen_shared',
              target          = 'ingen_shared',
              vnum            = '0.0.0',
              install_path    = '${LIBDIR}',
              lib             = ['dl'])
    autowaf.use_lib(bld, obj, 'GLIBMM LV2 LILV RAUL SORD LV2_MIDI')

    obj.source = '''
            AtomReader.cpp
            AtomWriter.cpp
            Builder.cpp
            ClashAvoider.cpp
            Configuration.cpp
            Forge.cpp
            LV2Features.cpp
            LV2URIMap.cpp
            Module.cpp
            ResourceImpl.cpp
            Store.cpp
            URIs.cpp
            World.cpp
            runtime_paths.cpp
    '''
