#!/usr/bin/env python
import autowaf

def build(bld):
	obj = bld.new_task_gen('cxx', 'program')
	obj.target       = 'ingen'
	obj.source       = 'main.cpp cmdline.c'
	obj.includes     = ['..', '../..', '../common']
	obj.defines      = 'VERSION="' + bld.env['INGEN_VERSION'] + '"'
	obj.uselib_local = 'libingen_module libingen_shared'
	obj.install_path = '${BINDIR}'
	autowaf.use_lib(bld, obj, 'GTHREAD GLIBMM REDLANDMM RAUL LV2CORE SLV2 INGEN LIBLO SOUP')
	
	bld.install_files('${DATADIR}/applications', 'ingen.desktop')

