#!/usr/bin/env python
from waflib.extras import autowaf as autowaf

def build(bld):
    obj = bld(features = 'c cxx cxxprogram')
    obj.target       = 'ingen'
    obj.source       = 'main.cpp'
    obj.includes     = ['..', '../..', '../../include']
    obj.defines      = 'VERSION="' + bld.env['INGEN_VERSION'] + '"'
    obj.use          = 'libingen_shared'
    obj.install_path = '${BINDIR}'
    autowaf.use_lib(bld, obj, 'GTHREAD GLIBMM SORD RAUL LV2CORE SLV2 INGEN LIBLO SOUP')

    bld.install_files('${DATADIR}/applications', 'ingen.desktop')
