#!/usr/bin/env python


def build(bld):
    obj = bld(features        = 'cxx cxxshlib',
              cflags          = ['-fvisibility=hidden'],
              includes        = ['../../include'],
              export_includes = ['../../include'],
              name            = 'libingen_client',
              target          = 'ingen_client',
              install_path    = '${LIBDIR}',
              use             = 'libingen',
              uselib          = 'GLIBMM LV2 LILV SUIL RAUL SERD SORD SIGCPP')

    obj.source = '''
        BlockModel.cpp
        ClientStore.cpp
        GraphModel.cpp
        ObjectModel.cpp
        PluginModel.cpp
        PluginUI.cpp
        PortModel.cpp
        ingen_client.cpp
    '''
