#!/usr/bin/env python
from waflib.extras import autowaf as autowaf

def build(bld):
    obj = bld(features        = 'cxx cxxshlib',
              includes        = ['../..'],
              export_includes = ['../..'],
              name            = 'libingen_client',
              target          = 'ingen_client',
              install_path    = '${LIBDIR}',
              use             = 'libingen')
    autowaf.use_lib(bld, obj, 'GLIBMM LV2 LILV SUIL RAUL SERD SORD SIGCPP')

    obj.source = '''
        BlockModel.cpp
        ClientStore.cpp
        GraphModel.cpp
        ObjectModel.cpp
        PluginModel.cpp
        PluginUI.cpp
        PortModel.cpp
        ingen_client.cpp
    '''
