#!/usr/bin/env python
import autowaf

def build(bld):
	# Headers
	bld.install_files('${INCLUDEDIR}/ingen/module', bld.path.ant_glob('*.hpp'))

	obj = bld(features = 'cxx cxxshlib')
	obj.source = '''
		World.cpp
		ingen_module.cpp
	'''
	obj.export_includes = ['.']
	obj.includes	    = ['.', '..', '../..', '../common']
	obj.name	    = 'libingen_module'
	obj.target	    = 'ingen_module'
	obj.vnum	    = '0.0.0'
	obj.use             = 'libingen_shared'
	obj.install_path    = '${LIBDIR}'
	autowaf.use_lib(bld, obj, 'GLIBMM LV2CORE SLV2 RAUL REDLANDMM')

