#!/usr/bin/env python
import autowaf

def build(bld):
	obj = bld.new_task_gen('cxx', 'shlib')
	obj.source = '''
		Module.cpp
		global.cpp
	'''
	obj.export_incdirs = ['.']
	obj.includes     = ['.', '..', '../common']
	obj.name         = 'libingen_module'
	obj.target       = 'ingen_module'
	obj.vnum         = '0.0.0'
	obj.uselib_local = 'libingen_shared'
	obj.install_path = '${LIBDIR}'
	autowaf.use_lib(bld, obj, 'GLIBMM LV2CORE SLV2 RAUL REDLANDMM')

